---
# Setup LVM partition

- name: Create a volume group on top of /dev/sda
  become: yes
  lvg:
    vg: "{{ lvm_vgname }}"
    pvs: /dev/sda1
    pesize: 32

- name: storage | create logical volume
  become: yes
  lvol:
    vg: "{{ lvm_vgname }}"
    lv: "{{ lvm_lvname }}"
    size: "{{ lvm_lvsize }}"
    shrink: "{{ lvm_shrink | default(True) }}"
    opts: "{{ lvm_lvopts | default(None) }}"

- name: storage | filesystem
  become: yes
  filesystem:
    fstype: "{{ lvm_lvfilesystem }}"
    dev: /dev/{{ lvm_vgname }}/{{ lvm_lvname }}
    resizefs: yes

- name: storage | mount
  become: yes
  mount:
    name: "{{ lvm_lvmount }}"
    src: /dev/{{ lvm_vgname }}/{{ lvm_lvname }}
    dump: "1"
    passno: "2"
    fstype: "{{ lvm_lvfilesystem }}"
    state: mounted
